version: "1.0"
services:
  postgres:
    image: "postgres:14.2"
    restart: always
    environment:
      - POSTGRES_USER=watch-user
      - POSTGRES_DB=watch-user
      - POSTGRES_PASSWORD=123
    ports:
      - "8083:5432"