spring:
  datasource:
    url: jdbc:h2:mem:watchwatt
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    show-sql: false
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  error:
    include-stacktrace: on_param
    include-message: always
