spring:
  datasource:
    url: jdbc:postgresql://localhost:8083/watch-user
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    sql:
      init:
        mode: always
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}
      roles: ${SECURITY_ROLE}
server:
  servlet:
    context-path: /api/watchwatt/
  port: 8080
  error:
    include-stacktrace: on_param
    include-message: always

jwt:
  token:
    key: ${JTW_TOKEN_KEY}
    expiration: ${JWT_TOKEN_EXPIRATION}
