spring:
  datasource:
    url: jdbc:postgresql://localhost:8083/watch-user
    username: watch-user
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    sql:
      init:
        mode: always
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false
  security:
    user:
      name: fiap
      password: fiap
      roles: manager
server:
  servlet:
    context-path: /api/watchwatt/
  port: 8080
  error:
    include-stacktrace: on_param
    include-message: always

jwt:
  token:
    key: watchwatt4d1381e44ae829040b6568e9e2b2cfa72c2f95946a04a760key
    expiration: 3600000

