spring:
  datasource:
    url: jdbc:postgresql://localhost:8083/watch-user
    username: watch-user
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    sql:
      init:
        mode: always
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false
server:
  servlet:
    context-path: /api/watchwatt/
  port: 8080
  error:
    include-stacktrace: on_param
    include-message: always
