spring:
  datasource:
    url: jdbc:h2:mem:watchwatt
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      fail-on-unknown-properties: false

server:
  servlet:
    context-path: /api/watchwatt/
  port: 8080
  error:
    include-stacktrace: on_param
    include-message: always