create table tb_user
(
    id           bigint generated by default as identity,
    birthday     date,
    cpf          bigint,
    date_created timestamp(6),
    email        varchar(255),
    gender       varchar(255),
    name         varchar(255),
    password     varchar(255),
    primary key (id)
);

create table tb_address
(
    id           bigint generated by default as identity,
    city         varchar(255),
    neighborhood varchar(255),
    number       integer,
    state        varchar(255),
    street       varchar(255),
    zip_code     varchar(255),
    primary key (id)
);

create table tb_appliance
(
    id    bigint generated by default as identity,
    model varchar(255),
    name  varchar(255),
    power integer not null,
    primary key (id)
);

